# -*- coding: utf-8 -*-
"""LlamaIndex Langchain Groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JKnwLwF_EdU_o1TjpHRuJ1Pfc_jhf5e

```markdown
# LlamaIndex RAG Chatbot with Groq and HuggingFace Embeddings

This notebook demonstrates how to build a Retrieval Augmented Generation (RAG) chatbot using LlamaIndex, powered by Groq's LLM and HuggingFace embeddings.

## Project Overview

This project allows you to interact with your PDF documents by asking questions. The chatbot will retrieve relevant information from your PDFs and provide answers. It leverages:

*   **LlamaIndex:** A data framework for LLM applications to easily build and query indexes over your data.
*   **Groq:** A high-performance LPU inference engine for fast LLM responses (using `llama-3.1-8b-instant`).
*   **HuggingFace Embeddings:** Local embeddings for efficient semantic search (using `BAAI/bge-small-en-v1.5`).

## Setup and Installation

1.  **Install Dependencies:** The notebook begins by installing necessary Python libraries.
    ```bash
    !pip uninstall -y langchain langchain-core langchain-community langchain-groq llama-index llama-index-core
    !pip cache purge
    !pip install -q llama-index llama-index-core llama-index-embeddings-huggingface llama-index-llms-langchain llama-index-readers-file langchain-community langchain-groq pypdf nest_asyncio openpyxl
    ```

2.  **Configure API Key:**
    *   Obtain a **Groq API Key** from [Groq Console](https://console.groq.com/keys).
    *   In Google Colab, go to `🔑 Secrets` on the left sidebar.
    *   Add a new secret named `GROQ_API_KEY` and paste your Groq API key there.

3.  **Initialize Models:** The notebook then initializes the HuggingFace embedding model and configures the Groq LLM.
    ```python
    import os
    import nest_asyncio
    from google.colab import userdata
    from llama_index.core import Settings
    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
    from langchain_groq import ChatGroq

    nest_asyncio.apply()

    GROQ_API_KEY = userdata.get("GROQ_API_KEY")
    os.environ["GROQ_API_KEY"] = GROQ_API_KEY
    
    Settings.embed_model = HuggingFaceEmbedding(
        model_name="BAAI/bge-small-en-v1.5"
    )

    Settings.llm = ChatGroq(
        api_key=GROQ_API_KEY,
        model_name="llama-3.1-8b-instant",
        temperature=0
    )
    print("🎉 [SUKSES] Seluruh konfigurasi model siap digunakan!")
    ```

## How to Use

1.  **Upload Your PDFs:**
    *   Create a folder named `data` in your Google Colab environment (if it doesn't exist).
    *   Upload your PDF documents into the `data` folder using the Colab file browser.

2.  **Run the RAG System:**
    *   Execute the cell that reads the PDF files, builds the vector index, and initializes the query engine.
    ```python
    import os
    from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

    if not os.path.exists("data") or len(os.listdir("data")) == 0:
        os.makedirs("data", exist_ok=True)
        print("PERINGATAN: Folder 'data' kosong atau tidak ditemukan.")
        print("Silakan upload file PDF Anda ke dalam folder 'data' di panel kiri Google Colab terlebih dahulu, lalu jalankan ulang cell ini.")
    else:
        print("[INFO] Membaca file PDF dari folder 'data'...")
        documents = SimpleDirectoryReader("data").load_data()
        print(f"[INFO] Sukses membaca dokumen. Total: {len(documents)} halaman terdeteksi.")
        print("[INFO] Membangun Vector Index di latar belakang...")

        index = VectorStoreIndex.from_documents(documents)
        query_engine = index.as_query_engine(similarity_top_k=3)
        print("[INFO] Sistem RAG Berhasil Diaktifkan!")
        print("\n" + "="*50)
        print("🤖 CHATBOT RAG DOKUMEN AKTIF")
        print("Ketik pertanyaan Anda lalu tekan ENTER.")
        print("Ketik 'exit' untuk menyudahi percakapan.")
        print("="*50 + "\n")

        while True:
            question = input("Kamu: ").strip()
            if question.lower() == 'exit':
                print("Sesi chat diakhiri. Sampai jumpa!")
                break
            if not question:
                continue
            print("\n[Sistem]: Sedang mencari referensi di PDF dan merumuskan jawaban...")
            try:
                response = query_engine.query(question)
                print(f"\nBot: {response}")
                print("\n" + "-"*40 + "\n")
            except Exception as e:
                print(f"\n[ERROR]: Terjadi kendala komunikasi dengan API: {e}\n")
    ```

3.  **Start Chatting:** Once the RAG system is active, you can type your questions in the input prompt. To exit the chat, type `exit`.

Enjoy interacting with your documents!
```
"""

!pip uninstall -y langchain langchain-core langchain-community langchain-groq llama-index llama-index-core
!pip cache purge
!pip install -q llama-index llama-index-core llama-index-embeddings-huggingface llama-index-llms-langchain llama-index-readers-file langchain-community langchain-groq pypdf nest_asyncio
!pip install -q llama-index llama-index-core llama-index-embeddings-huggingface llama-index-llms-langchain llama-index-readers-file langchain-community langchain-groq pypdf nest_asyncio openpyxl

import os
import nest_asyncio
from google.colab import userdata
from llama_index.core import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from langchain_groq import ChatGroq

nest_asyncio.apply()

GROQ_API_KEY = userdata.get("GROQ_API_KEY")
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print("[INFO] Memuat HuggingFace Embedding Lokal (BAAI/bge-small-en-v1.5)...")

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)
print("[INFO] Menghubungkan ke Groq Cloud LLM (llama-3.1-8b-instant)...")

Settings.llm = ChatGroq(
    api_key=GROQ_API_KEY,
    model_name="llama-3.1-8b-instant",
    temperature=0
)
print("\n🎉 [SUKSES] Seluruh konfigurasi model siap digunakan!")

import os
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

if not os.path.exists("data") or len(os.listdir("data")) == 0:
    os.makedirs("data", exist_ok=True)
    print("PERINGATAN: Folder 'data' kosong atau tidak ditemukan.")
    print("Silakan upload file PDF Anda ke dalam folder 'data' di panel kiri Google Colab terlebih dahulu, lalu jalankan ulang cell ini.")
else:
    print("[INFO] Membaca file PDF dari folder 'data'...")
    documents = SimpleDirectoryReader("data").load_data()
    print(f"[INFO] Sukses membaca dokumen. Total: {len(documents)} halaman terdeteksi.")
    print("[INFO] Membangun Vector Index di latar belakang...")

    index = VectorStoreIndex.from_documents(documents)
    query_engine = index.as_query_engine(similarity_top_k=3)
    print("[INFO] Sistem RAG Berhasil Diaktifkan!")
    print("\n" + "="*50)
    print("🤖 CHATBOT RAG DOKUMEN AKTIF")
    print("Ketik pertanyaan Anda lalu tekan ENTER.")
    print("Ketik 'exit' untuk menyudahi percakapan.")
    print("="*50 + "\n")

    while True:
        question = input("Kamu: ").strip()
        if question.lower() == 'exit':
            print("Sesi chat diakhiri. Sampai jumpa!")
            break
        if not question:
            continue
        print("\n[Sistem]: Sedang mencari referensi di PDF dan merumuskan jawaban...")
        try:
            response = query_engine.query(question)
            print(f"\nBot: {response}")
            print("\n" + "-"*40 + "\n")
        except Exception as e:
            print(f"\n[ERROR]: Terjadi kendala komunikasi dengan API: {e}\n")

